version: "3.9"

services:
  mysql:
    image: mysql:8.1
    container_name: edo_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: edo_language_academy
      MYSQL_USER: edo_user
      MYSQL_PASSWORD: strongpassword123
    ports:
      - "3307:3306" # ðŸ‘ˆ THIS IS THE FIX
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
